import Head from "next/head";
import Store from "../components/Store";
import Header from "../components/Header";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className="h-screen bg-primary-50">
      <Head>
        <title>Solana Books Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Store />
      <Footer />
    </div>
  );
}
